#!/bin/sh

uci -q show system.@watchcat[0] || {
	uci add system watchcat
	uci set system.@watchcat[0].period=6h
	uci set system.@watchcat[0].mode=ping
	uci set system.@watchcat[0].pinghosts=119.29.29.29
	uci set system.@watchcat[0].forcedelay=30
	uci commit
}
