#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2008 OpenWrt.org

START=60

DEFAULT_SERVERS="0.openwrt.pool.ntp.org 1.openwrt.pool.ntp.org 2.openwrt.pool.ntp.org"
TIMEOUT="2" # in seconds

start() {
	local cfg_servers step_servers

	cfg_servers=$(uci -q get system.ntp.server)
	step_servers=${cfg_servers:-$DEFAULT_SERVERS}

	for s in $step_servers ; do
		/usr/sbin/ntpdate -s -b -u -t "$TIMEOUT" "$s" && break
	done
}
